### ISSUE TITLE
Needs an explicit license

### ISSUE THREAD

**Issue by adamwight** [jdlrobson/wikipedia-react-components#7]
Thanks for the great library, I've started using it in https://github.com/wiki-ai/ores-reference-ui.  Would you add a license file, when you get the chance?

**Comment by jdlrobson** [comment]
Sorry. Wasn't pushed https://github.com/jdlrobson/wikipedia-react-components/commit/ccf1b29a8cfa324b8c55cf4cb282316d976847c0

**Comment by adamwight** [comment]
Great!  Funny thing, I was just running "license-report" on our dependencies and it kept returning "GPL-2.0+" for your repo, which didn't make any sense until just now :-)
